name: Release From Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set Release Tag
        run: export RTAG=testing
          
      - name: Get Binaries
        run: |
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-solvers-centos6-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-lib-centos6-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-solvers-centos7-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-lib-centos7-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-solvers-centos8-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-lib-centos8-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-solvers-ubuntu1804-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-lib-ubuntu1804-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-solvers-ubuntu1910-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-lib-ubuntu1910-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-solvers-ubuntu2004-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-lib-ubuntu2004-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-solvers-windows-64.tar.gz
          wget https://github.com/IDAES/idaes-ext/releases/download/test-release/idaes-lib-windows-64.tar.gz
         
      - name: Calculate Hashes
        run: |
          sha256sum idaes-lib-centos6-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-solvers-centos6-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-lib-centos7-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-solvers-centos7-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-lib-centos8-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-solvers-centos8-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-lib-ubuntu1804-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-solvers-ubuntu1804-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-lib-ubuntu1910-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-solvers-ubuntu1910-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-lib-ubuntu2004-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-solvers-ubuntu2004-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-lib-windows-64.tar.gz >> sha256sum_${RTAG}.txt
          sha256sum idaes-solvers-windows-64.tar.gz >> sha256sum_${RTAG}.txt
          
      - name: Push Hashes
        run: |
          git checkout https://github.com/idaes/idaes-ext
          cd idaes-ext/releases
          cp ../../sha256sum_${RTAG}.txt ./
          git add sha256sum_${RTAG}.txt
          git commit -m "Add release hashes"
          git push origin main
          
