
name: macOS Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install boost and bash
        run: |
          brew install boost
          brew install bash
          brew install pkgconfig
      - name: Make src directory
        run: mkdir ~/src
      - name: Get/Build PETSc
        run: |
          cd ~/src
          which gfortran-13
          ln -s /usr/local/bin/gfortran-13 /usr/local/bin/gfortran
          wget https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.19.2.tar.gz
          tar -zxf petsc-3.19.2.tar.gz
          cd petsc-3.19.2
          ./configure --with-debug=0 --with-shared=0 --with-mpi=0 --with-fortran-bindings=0 --download-metis --download-mumps --with-mumps-serial=1 --prefix=$HOME/src/petsc-dist
          make
          make install
      - name: Checkout IDAES-EXT
        run: |
          cd ~/src
          git clone https://github.com/idaes/idaes-ext
          cd idaes-ext
          sh ./scripts/build_directory.sh ~/src/idaes-ext-build
      - name: Build IDAES-EXT
        run: |
          cd ~/src/idaes-ext-build
          bash ./scripts/compile_solvers.sh darwin
          bash ./scripts/compile_libs.sh darwin
          bash ./scripts/mac_collect_x86_64.sh
      - name: Upload lib
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: idaes-lib-darwin-x86_64.tar.gz
          path: ~/src/idaes-ext-build/idaes-lib-darwin-x86_64.tar.gz
          retention-days: 4
      - name: Upload solvers
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: idaes-solvers-darwin-x86_64.tar.gz
          path: ~/src/idaes-ext-build/idaes-solvers-darwin-x86_64.tar.gz
          retention-days: 4
      - name: Upload petsc
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: idaes-petsc-darwin-x86_64.tar.gz
          path: ~/src/idaes-ext-build/idaes-petsc-darwin-x86_64.tar.gz
          retention-days: 4
