
name: macOS Build

on: [workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install boost
        run: brew install boost
      - name: Make src directory
        run: mkdir src
      - name: Get/Build PETSc
        run: |
          cd src
          which gfortran-12
          ln -s /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
          wget https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.18.4.tar.gz
          tar -zxf petsc-3.18.4.tar.gz
          cd petsc-3.18.4
          ./configure --with-debug=0 --with-shared=0 --with-mpi=0 --with-fortran-bindings=0 --download-metis --download-mumps --with-mumps-serial=1 --prefix=$HOME/src/petsc-dist
          make
          make install
      - name: 'Upload Artifact'
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: petsc_config_log
          path: src/petsc-3.18.1/configure.log
          retention-days: 1
