
name: macOS Build

on: [workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install boost
        run: brew install boost
      - name: Make src directory
        run: mkdir src
      - name: Get/Build PETSc
        run: |
          cd src
          wget https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.18.1.tar.gz
          tar -zxf petsc-3.18.1.tar.gz
          cd petsc-3.18.1
          ./configure --with-debug=0 --with-shared=0 --with-mpi=0 --with-fortran-bindings=0 --download-metis --download-mumps --with-mumps-serial=1 --prefix=$HOME/src/petsc-dist
          make
          make install
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: petsc_config_log
          path: configure.log
          retention-days: 1
