name: test_centos6_refactor.py

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./docker/test-extensions/centos6

      - name: Check OS
        run: docker run eslickj/idaes-ext-centos6-test:latest bash -c cat /etc/redhat-release

      - name: "Test Have Pynumero"
        run: |
          docker run eslickj/idaes-ext-centos6-test:latest bash -c '
            cd /repo/idaes-pse/idaes
            eval "$(/root/miniconda/bin/conda shell.bash hook)"
            conda activate idaes
            pytest tests/test_have_pynumero.py'

      - name: "Test Have Ipopt"
        run: |
          docker run eslickj/idaes-ext-centos6-test:latest bash -c '
            cd /repo/idaes-pse/idaes
            eval "$(/root/miniconda/bin/conda shell.bash hook)"
            conda activate idaes
            pytest tests/test_ipopt.py'

      - name: "Test Core"
        run: |
          docker run eslickj/idaes-ext-centos6-test:latest bash -c '
            cd /repo/idaes-pse/idaes/core
            eval "$(/root/miniconda/bin/conda shell.bash hook)"
            conda activate idaes
            pytest

      - name: "Test Generic Models"
        run: |
          docker run eslickj/idaes-ext-centos6-test:latest bash -c '
            d /repo/idaes-pse/idaes/generic_models
            eval "$(/root/miniconda/bin/conda shell.bash hook)"
            conda activate idaes
            pytest
