name: test_centos6_refactor.py

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://eslickj/idaes-ext-centos6-test:latest

      - name: Start Docker container
        run: docker run -it eslickj/idaes-ext-centos6-test:latest bash

      - name: Check OS
        run: cat /etc/redhat-release

      - name: Set up to run Conda
        run: |
          eval "$(/root/miniconda/bin/conda shell.bash hook)"
          cd /repo
          conda create -n idaes python=3.7.4 pip psutil
          conda activate idaes

      - name: "Install IDAES-PSE"
        run: |
          git clone https://github.com/idaes/idaes-pse.git
          cd idaes-pse
          git checkout master
          pip install -e .
          idaes get-extensions --url https://github.com/IDAES/idaes-ext/releases/download/test-release/ --platform centos6

      - name: "Test Have Pynumero"
        run: |
            cd /repo/idaes-pse/idaes
            pytest tests/test_have_pynumero.py

      - name: "Test Have Ipopt"
        run: |
            pytest tests/test_ipopt.py

      - name: "Test Core"
        run: |
            cd /repo/idaes-pse/idaes/core
            pytest

      - name: "Test Generic Models"
        run: |
            cd /repo/idaes-pse/idaes/generic_models
            pytest

      - name: "Exit Docker Container"
        run: exit
