name: Windows Test IDAES-PSE PyPI

on: [workflow_dispatch]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: "Install IDAES-PSE"
        shell: cmd
        run: |
          pip install idaes-pse
          idaes get-extensions --url https://github.com/IDAES/idaes-ext/releases/download/test-release/

      - name: "Test IDAES-PSE"
        shell: cmd
        run: |
          pytest --pyargs idaes -W ignore
