name: Test Windows

on: [workflow_dispatch]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: "Install Miniconda"
        shell: powershell
        run: |
          Invoke-WebRequest -UserAgent 'DockerCI' -outfile Miniconda3-latest-Windows-x86_64.exe https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
          Start-Process Miniconda3-latest-Windows-x86_64 -ArgumentList '/InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3' -Wait
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          cmd /c %UserProfile%\Miniconda3\condabin\conda.bat init
          cmd /c conda create -n idaes python=3.7.4 pip psutil git pytest

      - name: "Clone/Install IDAES-PSE"
        shell: cmd
        run: |
          conda activate idaes
          git clone https://github.com/idaes/idaes-pse.git
          cd idaes-pse
          git checkout master
          pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt
          pip install -e .
          idaes get-extensions --url https://github.com/IDAES/idaes-ext/releases/download/test-release/

      - name: "Test IDAES-PSE"
        shell: cmd
        run: |
          conda activate idaes
          cd idaes-pse\idaes
          pytest
